### ISSUE TITLE
'Process' object has no attribute 'kill'

### ISSUE THREAD

**Issue by lukaskawerau** [pirate/ArchiveBox#132]
**Describe the bug**
When using ArchiveBox on macOS, I get the error `AttributeError: 'Process' object has no attribute 'kill'`. This happens for every archiving method. If `Favicon` is active, this means the process fails to capture the webpage using `wget`. Only repeating the command helps.

**To Reproduce**
```
lukas$ echo 'https://idlewords.com/2018/12/gluten_free_antarctica.htm' | /Users/lukas/coding/ArchiveBox/archive
[+] [2019-01-22 14:21:43] Adding 1 new links from output/sources/stdin-1548163303.txt to output/index.json
[√] [2019-01-22 14:21:44] Updated main index files:
    > output/index.json
    > output/index.html
[▶] [2019-01-22 14:21:44] Updating files for 1 links in archive...
[+] [2019-01-22 14:21:44] "https://idlewords.com/2018/12/gluten_free_antarctica.htm"
    https://idlewords.com/2018/12/gluten_free_antarctica.htm
    > output/archive/1548163303 (new)
      > favicon
                                                                                                     0.2% (0/60sec)[X] [2019-01-22 14:21:44] Downloading paused on link 1548163303 (1/1)
    Continue where you left off by running:
        archive 1548163303
Traceback (most recent call last):
  File "/Users/lukas/coding/ArchiveBox/archivebox/archive_methods.py", line 464, in fetch_favicon
    end()
  File "/Users/lukas/coding/ArchiveBox/archivebox/util.py", line 173, in end
    p.kill()
AttributeError: 'Process' object has no attribute 'kill'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lukas/coding/ArchiveBox/archive", line 202, in <module>
    update_archive(out_dir, links, source=source, resume=resume, append=True)
  File "/Users/lukas/coding/ArchiveBox/archive", line 112, in update_archive
    archive_links(archive_path, links, source=source, resume=resume)
  File "/Users/lukas/coding/ArchiveBox/archivebox/archive_methods.py", line 76, in archive_links
    raise e
  File "/Users/lukas/coding/ArchiveBox/archivebox/archive_methods.py", line 60, in archive_links
    archive_link(link_dir, link)
  File "/Users/lukas/coding/ArchiveBox/archivebox/archive_methods.py", line 95, in archive_link
    link = fetch_favicon(link_dir, link, overwrite=overwrite)
  File "/Users/lukas/coding/ArchiveBox/archivebox/archive_methods.py", line 161, in timed_fetch_func
    result = fetch_func(link_dir, link, **kwargs)
  File "/Users/lukas/coding/ArchiveBox/archivebox/archive_methods.py", line 469, in fetch_favicon
    end()
  File "/Users/lukas/coding/ArchiveBox/archivebox/util.py", line 173, in end
                                                                                                     0.2% (0/60sec)    p.kill()
AttributeError: 'Process' object has no attribute 'kill'
```

**Expected behavior**
ArchiveBox should archive without problems.
When repeating the command ArchiveBox _does work_, I do get HTML and WARC etc. but only when repeating the command for every archive method I have active.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Browser: Chromium 73.0.3681.0 

**Additional context**
Config File:

```
CHROME_BINARY=/usr/local/bin/chromium-browser
RESOLUTION=1440,900
FETCH_PDF=False
FETCH_WARC=True
FETCH_WGET_REQUISITES=True
FETCH_WGET=True
SUBMIT_ARCHIVE_DOT_ORG=True
OUTPUT_DIR=/Users/lukas/Documents/bookmarks
```

**Comment by lukaskawerau** [comment]
That fixes it, thank you!
