### ISSUE TITLE
No module named 'crontab'

### ISSUE THREAD

**Issue by datakid** [pirate/ArchiveBox#224]
Fresh git pull of the django branch, missing the django-crontab module?

```
Traceback (most recent call last):
  File "./bin/archivebox", line 6, in <module>
    from .cli import archivebox
  File "/opt/ArchiveBox_django/archivebox/__init__.py", line 4, in <module>
    from . import cli
  File "/opt/ArchiveBox_django/archivebox/cli/__init__.py", line 59, in <module>
    SUBCOMMANDS = list_subcommands()
  File "/opt/ArchiveBox_django/archivebox/cli/__init__.py", line 34, in list_subcommands
    module = import_module('.archivebox_{}'.format(subcommand), __package__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/ArchiveBox_django/archivebox/cli/archivebox_schedule.py", line 12, in <module>
    from ..main import schedule
  File "/opt/ArchiveBox_django/archivebox/main.py", line 10, in <module>
    from crontab import CronTab, CronSlices
ModuleNotFoundError: No module named 'crontab'
```

**Comment by datakid** [comment]
`apt install python3-crontab` fixes this issue.

**Comment by datakid** [comment]
I worked this out. Git pull, checkout django branch. `pip install -e .` and it all works.
