### ISSUE TITLE
No module named 'mypy_extensions'

### ISSUE THREAD

**Issue by datakid** [pirate/ArchiveBox#225]
```
$ ./archive.sh https://boingboing.net
Traceback (most recent call last):
  File "/opt/ArchiveBox_django/bin/archivebox", line 6, in <module>
    from .cli import archivebox
  File "/opt/ArchiveBox_django/archivebox/__init__.py", line 4, in <module>
    from . import cli
  File "/opt/ArchiveBox_django/archivebox/cli/__init__.py", line 59, in <module>
    SUBCOMMANDS = list_subcommands()
  File "/opt/ArchiveBox_django/archivebox/cli/__init__.py", line 34, in list_subcommands
    module = import_module('.archivebox_{}'.format(subcommand), __package__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/ArchiveBox_django/archivebox/cli/archivebox_schedule.py", line 12, in <module>
    from ..main import schedule
  File "/opt/ArchiveBox_django/archivebox/main.py", line 20, in <module>
    from .index.schema import Link
  File "/opt/ArchiveBox_django/archivebox/index/__init__.py", line 13, in <module>
    from ..parsers import parse_links
  File "/opt/ArchiveBox_django/archivebox/parsers/__init__.py", line 13, in <module>
    from ..config import TIMEOUT
  File "/opt/ArchiveBox_django/archivebox/config/__init__.py", line 16, in <module>
    from .stubs import (
  File "/opt/ArchiveBox_django/archivebox/config/stubs.py", line 2, in <module>
    from mypy_extensions import TypedDict
ModuleNotFoundError: No module named 'mypy_extensions'
```

Requires `pip install mypy-extensions`

**Comment by datakid** [comment]
This is my bad again - git pull the repo and `pip install -e .` solves this

**Comment by pirate** [comment]
:+1: Also FYI on [v0.4.0](https://github.com/pirate/ArchiveBox/pull/207) you can also use `pipenv install --dev` to set everything up.
