### ISSUE TITLE
"No such file or directory" on favicon in virtualenv

### ISSUE THREAD

**Issue by anarcat** [pirate/ArchiveBox#232]
#### Describe the bug

I installed archivebox from pip (yaaay!) and couldn't do the original setup, which failed at the `archivebox init` step with:

FileNotFoundError: [Errno 2] No such file or directory: '/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/themes/legacy/favicon.ico'

#### Steps to reproduce

1. setup a virtual env with `virtualenv --python=python3 ~/.virtualenvs/archivebox`
2. installed archivebox with `~/.virtualenvs/archivebox/pip3 install archivebox`, which correctly installed archivebox 0.4.1
3. ran `archivebox init` which crashed with the aforementioned error message

#### Screenshots or log output

```
anarcat@curie:~(master)$ virtualenv --python=python3  ~/.virtualenvs/archivebox
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/anarcat/.virtualenvs/archivebox/bin/python3
Also creating executable in /home/anarcat/.virtualenvs/archivebox/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
anarcat@curie:~(master)$ ~/.virtualenvs/archivebox/bin/pip3 install archivebox
Collecting archivebox
  Downloading https://files.pythonhosted.org/packages/5f/64/e588fb64a1fee9d40b0e0c51a99e9f7879ee64786370cd3e9f83cfe61031/archivebox-0.4.1-py3-none-any.whl (314kB)
     |████████████████████████████████| 317kB 1.8MB/s 
Collecting base32-crockford==0.3.0 (from archivebox)
  Downloading https://files.pythonhosted.org/packages/4d/6f/7ad1176c56c920e9841b14923f81545a4243876628312f143915561770d2/base32_crockford-0.3.0-py2.py3-none-any.whl
Collecting django-extensions==2.1.6 (from archivebox)
  Downloading https://files.pythonhosted.org/packages/26/66/613b34aa7246e1be223e7f539212d8972e41046ec7f2b8bc0ba3e2cfcf22/django_extensions-2.1.6-py2.py3-none-any.whl (218kB)
     |████████████████████████████████| 225kB 2.5MB/s 
Collecting mypy-extensions==0.4.1 (from archivebox)
  Downloading https://files.pythonhosted.org/packages/4d/72/8d54e2b296631b9b14961d583e56e90d9d7fba8a240d5ce7f1113cc5e887/mypy_extensions-0.4.1-py2.py3-none-any.whl
Collecting youtube-dl (from archivebox)
  Downloading https://files.pythonhosted.org/packages/ad/1f/ae3e500935979bec629bab80be8b6fea00f7d5e8cb29564cf0f9c5afe975/youtube_dl-2019.4.30-py2.py3-none-any.whl (1.8MB)
     |████████████████████████████████| 1.8MB 2.6MB/s 
Collecting django==2.2 (from archivebox)
  Downloading https://files.pythonhosted.org/packages/54/85/0bef63668fb170888c1a2970ec897d4528d6072f32dee27653381a332642/Django-2.2-py3-none-any.whl (7.4MB)
     |████████████████████████████████| 7.5MB 2.5MB/s 
Collecting ipython (from archivebox)
  Downloading https://files.pythonhosted.org/packages/a9/2e/41dce4ed129057e05a555a7f9629aa2d5f81fdcd4d16568bc24b75a1d2c9/ipython-7.5.0-py3-none-any.whl (770kB)
     |████████████████████████████████| 778kB 3.0MB/s 
Collecting dataclasses==0.6 (from archivebox)
  Downloading https://files.pythonhosted.org/packages/26/2f/1095cdc2868052dd1e64520f7c0d5c8c550ad297e944e641dbf1ffbb9a5d/dataclasses-0.6-py3-none-any.whl
Collecting python-crontab==2.3.6 (from archivebox)
  Downloading https://files.pythonhosted.org/packages/2c/4f/60b3481b00af6cb91eb19bfb14ac518aebd268fa2a0cd3e21ba1687c4816/python-crontab-2.3.6.tar.gz (44kB)
     |████████████████████████████████| 51kB 4.7MB/s 
Collecting six>=1.2 (from django-extensions==2.1.6->archivebox)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pytz (from django==2.2->archivebox)
  Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
     |████████████████████████████████| 512kB 2.9MB/s 
Collecting sqlparse (from django==2.2->archivebox)
  Downloading https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Collecting backcall (from ipython->archivebox)
Collecting pexpect; sys_platform != "win32" (from ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 3.8MB/s 
Collecting decorator (from ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting prompt-toolkit<2.1.0,>=2.0.0 (from ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/f7/a7/9b1dd14ef45345f186ef69d175bdd2491c40ab1dfa4b2b3e4352df719ed7/prompt_toolkit-2.0.9-py3-none-any.whl (337kB)
     |████████████████████████████████| 337kB 3.0MB/s 
Collecting pygments (from ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)
     |████████████████████████████████| 849kB 2.9MB/s 
Collecting traitlets>=4.2 (from ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl (74kB)
     |████████████████████████████████| 81kB 3.7MB/s 
Requirement already satisfied: setuptools>=18.5 in ./.local/share/virtualenvs/archivebox/lib/python3.7/site-packages (from ipython->archivebox) (41.0.1)
Collecting jedi>=0.10 (from ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/25/2b/1f188901be099d52d7b06f4d3b7cb9f8f09692c50697b139eaf6fa2928d8/jedi-0.13.3-py2.py3-none-any.whl (178kB)
     |████████████████████████████████| 184kB 3.0MB/s 
Collecting pickleshare (from ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting python-dateutil (from python-crontab==2.3.6->archivebox)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
     |████████████████████████████████| 235kB 3.0MB/s 
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.1.0,>=2.0.0->ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting ipython-genutils (from traitlets>=4.2->ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting parso>=0.3.0 (from jedi>=0.10->ipython->archivebox)
  Downloading https://files.pythonhosted.org/packages/a7/bd/e2f4753c5fa93932899243b4299011a757ac212e9bc8ddf062f38df4e78b/parso-0.4.0-py2.py3-none-any.whl (94kB)
     |████████████████████████████████| 102kB 3.1MB/s 
Building wheels for collected packages: python-crontab
  Building wheel for python-crontab (setup.py) ... done
  Stored in directory: /home/anarcat/.cache/pip/wheels/45/c2/12/4f9e435a355df948f562120991107677bf2dce1bb86b18e751
Successfully built python-crontab
Installing collected packages: base32-crockford, six, django-extensions, mypy-extensions, youtube-dl, pytz, sqlparse, django, backcall, ptyprocess, pexpect, decorator, wcwidth, prompt-toolkit, pygments, ipython-genutils, traitlets, parso, jedi, pickleshare, ipython, dataclasses, python-dateutil, python-crontab, archivebox
Successfully installed archivebox-0.4.1 backcall-0.1.0 base32-crockford-0.3.0 dataclasses-0.6 decorator-4.4.0 django-2.2 django-extensions-2.1.6 ipython-7.5.0 ipython-genutils-0.2.0 jedi-0.13.3 mypy-extensions-0.4.1 parso-0.4.0 pexpect-4.7.0 pickleshare-0.7.5 prompt-toolkit-2.0.9 ptyprocess-0.6.0 pygments-2.3.1 python-crontab-2.3.6 python-dateutil-2.8.0 pytz-2019.1 six-1.12.0 sqlparse-0.3.0 traitlets-4.3.2 wcwidth-0.1.7 youtube-dl-2019.4.30
anarcat@curie:archivebox(master)$ . ~/.virtualenvs/archivebox/bin/activate
anarcat@curie:archivebox(master)$ archivebox init
[+] Initializing a new ArchiveBox collection in this folder...
    /srv/backup/archive/archivebox
------------------------------------------------------------------

[+] Building archive folder structure...
    √ /srv/backup/archive/archivebox/sources
    √ /srv/backup/archive/archivebox/archive
    √ /srv/backup/archive/archivebox/logs
    √ /srv/backup/archive/archivebox/ArchiveBox.conf

[+] Building main SQL index and running migrations...
    √ /srv/backup/archive/archivebox/index.sqlite3

    Operations to perform:
      Apply all migrations: admin, auth, contenttypes, core, sessions
    Running migrations:
    Applying contenttypes.0001_initial... OK
    Applying auth.0001_initial... OK
    Applying admin.0001_initial... OK
    Applying admin.0002_logentry_remove_auto_add... OK
    Applying admin.0003_logentry_add_action_flag_choices... OK
    Applying contenttypes.0002_remove_content_type_name... OK
    Applying auth.0002_alter_permission_name_max_length... OK
    Applying auth.0003_alter_user_email_max_length... OK
    Applying auth.0004_alter_user_username_opts... OK
    Applying auth.0005_alter_user_last_login_null... OK
    Applying auth.0006_require_contenttypes_0002... OK
    Applying auth.0007_alter_validators_add_error_messages... OK
    Applying auth.0008_alter_user_username_max_length... OK
    Applying auth.0009_alter_user_last_name_max_length... OK
    Applying auth.0010_alter_group_name_max_length... OK
    Applying auth.0011_update_proxy_permissions... OK
    Applying core.0001_initial... OK
    Applying sessions.0001_initial... OK

[*] Collecting links from any existing indexes and archive folders...

[*] [2019-05-06 20:47:08] Writing 0 links to main index...
    √ /srv/backup/archive/archivebox/index.sqlite3                                                                                                                     
    √ /srv/backup/archive/archivebox/index.json                                                                                                                        
Traceback (most recent call last):                                                                                                                                     
  File "/home/anarcat/.virtualenvs/archivebox/bin/archivebox", line 10, in <module>
    sys.exit(main())
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/__main__.py", line 10, in main
    archivebox.main(args=sys.argv[1:], stdin=sys.stdin)
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/cli/archivebox.py", line 58, in main
    pwd=pwd or OUTPUT_DIR,
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/cli/__init__.py", line 55, in run_subcommand
    module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/cli/archivebox_init.py", line 34, in main
    out_dir=pwd or OUTPUT_DIR,
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/util.py", line 104, in typechecked_function
    return func(*args, **kwargs)
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/main.py", line 371, in init
    write_main_index(list(all_links.values()), out_dir=out_dir)
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/util.py", line 104, in typechecked_function
    return func(*args, **kwargs)
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/index/__init__.py", line 239, in write_main_index
    write_html_main_index(links, out_dir=out_dir, finished=finished)
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/util.py", line 104, in typechecked_function
    return func(*args, **kwargs)
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/index/html.py", line 56, in write_html_main_index
    copy_and_overwrite(join(TEMPLATES_DIR, FAVICON_FILENAME), join(out_dir, FAVICON_FILENAME))
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/util.py", line 104, in typechecked_function
    return func(*args, **kwargs)
  File "/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/system.py", line 106, in copy_and_overwrite
    with open(from_path, 'rb') as src:
FileNotFoundError: [Errno 2] No such file or directory: '/home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/themes/legacy/favicon.ico'
anarcat@curie:archivebox(master)$ archivebox version
ArchiveBox v0.4.1

[i] Dependency versions:
 √  PYTHON_BINARY          /home/anarcat/.virtualenvs/archivebox/bin/python3                            v3.7            valid 
 √  DJANGO_BINARY          /home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/django/bin/django-admin.py v2.2.0          valid 
 √  CURL_BINARY            /usr/bin/curl                                                                v7.64.0         valid 
 √  WGET_BINARY            /usr/bin/wget                                                                v1.20.1         valid 
 √  GIT_BINARY             /usr/bin/git                                                                 v2.20.1         valid 
 √  YOUTUBEDL_BINARY       /home/anarcat/.virtualenvs/archivebox/bin/youtube-dl                         v2019.04.30     valid 
 √  CHROME_BINARY          /usr/bin/chromium                                                            v73.0.3683.75   valid 

[i] Code locations:
 √  REPO_DIR               /home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages            62 files        valid 
 √  PYTHON_DIR             /home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox 15 files        valid 
 √  TEMPLATES_DIR          /home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/themes/legacy 1 files         valid 

[i] External locations:
 √  CHROME_USER_DATA_DIR   /home/anarcat/.config/chromium                                               26 files        valid 
 -  COOKIES_FILE                                                                                        -               disabled 

[i] Data locations:
 √  OUTPUT_DIR             /srv/backup/archive/archivebox                                               6 files         valid 
 √  SOURCES_DIR            /srv/backup/archive/archivebox/sources                                       0 files         valid 
 √  LOGS_DIR               /srv/backup/archive/archivebox/logs                                          0 files         valid 
 √  ARCHIVE_DIR            /srv/backup/archive/archivebox/archive                                       0 files         valid 
 √  CONFIG_FILE            /srv/backup/archive/archivebox/ArchiveBox.conf                               437.0 Bytes     valid 
 √  SQL_INDEX              /srv/backup/archive/archivebox/index.sqlite3                                 144.0 KB        valid 
 √  JSON_INDEX             /srv/backup/archive/archivebox/index.json                                    2.8 KB          valid 
 X  HTML_INDEX             /srv/backup/archive/archivebox/index.html                                    missing         invalid 

```

#### Software versions

 - OS: Debian 10 "buster", up to date (to today)
 - ArchiveBox version: 0.4.1, courageously installed from PyPI
 - Python version: 3.7.3rc1
 - Chrome version:  N/A

#### Workaround

Copy over the theme manually from the 0.4.1 tree:

```
git clone https://github.com/pirate/ArchiveBox/
git co v0.4.1
rsync -rv ./archivebox/themes/legacy/ /home/anarcat/.virtualenvs/archivebox/lib/python3.7/site-packages/archivebox/themes/legacy/
```

**Comment by anarcat** [comment]
sorry, the first version of this was just the template because i mistakenly hit "enter" before completing the report... great UI github. :)

**Comment by pirate** [comment]
Ah lol I should never have pushed v0.4.1 to production PyPi, I was too eager and I was just trying to test the packaging setup.  None of the versions in PyPi are ready for users. For now, just install from the django branch with `pip install -e .`.

**Comment by anarcat** [comment]
i think it's fine you pushed it to pypi, it made it possible for me to install it, but yeah - there are bugs. :) i would say that you should push that branch out to pypi already to fix that bug, even! ;)
