### ISSUE TITLE
adding txt file with multiple links throws JSONDecodeError

### ISSUE THREAD

**Issue by Strubbl** [pirate/ArchiveBox#245]
#### Describe the bug
Archiving a list of links does not work anymore. The links.txt consists of many URLs, one URL per line. The file is just a link per line and no JSON at all.

I try to add multiple links according to documentation: https://github.com/pirate/ArchiveBox/wiki/Usage#import-a-single-url-or-list-of-urls-via-stdin

#### Screenshots or log output

```
$ cat /data/archivebox/links.txt | docker run -i -v /data/archivebox/output:/data strubbl_archivebox /bin/archive
Traceback (most recent call last):
  File "/bin/archive", line 136, in <module>
    main(*sys.argv)
  File "/bin/archive", line 98, in main
    update_archive_data(import_path=import_path, resume=resume)
  File "/bin/archive", line 106, in update_archive_data
    all_links, new_links = load_links_index(out_dir=OUTPUT_DIR, import_path=import_path)
  File "/home/pptruser/app/archivebox/index.py", line 61, in load_links_index
    existing_links = parse_json_links_index(out_dir)
  File "/home/pptruser/app/archivebox/index.py", line 108, in parse_json_links_index
    links = json.load(f)['links']
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

#### Software versions

 - OS: Docker container
 - ArchiveBox version:        b109dd6

**Comment by pirate** [comment]
This looks like a corrupted index instead of a parsing error, can you post your redacted `index.json` file?

**Comment by Strubbl** [comment]
You are right. My index.json has the size of 0 bytes. I did not check that.

**Comment by pirate** [comment]
I thnik you hit this bug, you can follow the instructions on that ticket: https://github.com/pirate/ArchiveBox/issues/234
