### ISSUE TITLE
Wget missing despite following directions on docker-compose page?

### ISSUE THREAD

**Issue by shimizurei** [pirate/ArchiveBox#294]
## My Install Process on Synology DSM 6

```
User@IPAddr:/volume1/dkr$ git clone https://github.com/pirate/ArchiveBox && cd ArchiveBox
Cloning into 'ArchiveBox'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 4755 (delta 21), reused 3 (delta 0), pack-reused 4718
Receiving objects: 100% (4755/4755), 3.75 MiB | 7.48 MiB/s, done.
Resolving deltas: 100% (3124/3124), done.

User@IPAddr:/volume1/dkr/ArchiveBox$ mkdir data && chmod 777 data

/volume1/dkr/ArchiveBox$ sudo docker-compose up -d
Password:
Creating network "archivebox_default" with the default driver
Building archivebox
Step 1/17 : FROM node:11-slim
 ---> 1f1634a1b9c0
Step 2/17 : LABEL maintainer="Nick Sweeting <archivebox-git@sweeting.me>"
 ---> Using cache
 ---> e475d59f9a18
Step 3/17 : RUN apt-get update     && apt-get install -yq --no-install-recommends         git wget curl youtube-dl gnupg2 libgconf-2-4 python3 python3-pip     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> c285b80bb08c
Step 4/17 : RUN apt-get update && apt-get install -y wget --no-install-recommends     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'     && apt-get update     && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont       --no-install-recommends     && rm -rf /var/lib/apt/lists/*     && rm -rf /src/*.deb
 ---> Using cache
 ---> fc7d4fb1a388
Step 5/17 : ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init

 ---> 8f41f559d375
Step 6/17 : RUN chmod +x /usr/local/bin/dumb-init
 ---> Running in 3e363d2600d5
Removing intermediate container 3e363d2600d5
 ---> 7181b6a8ddb7
Step 7/17 : ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
 ---> Running in 2be880b6f424
Removing intermediate container 2be880b6f424
 ---> e984ae3dc0f7
Step 8/17 : RUN npm i puppeteer
 ---> Running in b5116eb2af14

> puppeteer@2.0.0 install /node_modules/puppeteer
> node install.js

**INFO** Skipping Chromium download. "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" environment variable was found.
npm WARN saveError ENOENT: no such file or directory, open '/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

+ puppeteer@2.0.0
added 43 packages from 22 contributors and audited 50 packages in 4.692s
found 0 vulnerabilities

Removing intermediate container b5116eb2af14
 ---> b75f1c9a10be
Step 9/17 : RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser     && mkdir -p /home/pptruser/Downloads     && chown -R pptruser:pptruser /home/pptruser     && chown -R pptruser:pptruser /node_modules
 ---> Running in 1aacf807028f
Removing intermediate container 1aacf807028f
 ---> 7ff9f381e09c
Step 10/17 : COPY . /home/pptruser/app
 ---> 83e6e5fd2558
Step 11/17 : RUN mkdir -p /data     && chown -R pptruser:pptruser /data     && ln -s /data /home/pptruser/app/archivebox/output     && ln -s /home/pptruser/app/bin/* /bin/     && ln -s /home/pptruser/app/bin/archivebox /bin/archive     && chown -R pptruser:pptruser /home/pptruser/app/archivebox
 ---> Running in f8ebfba3762a
Removing intermediate container f8ebfba3762a
 ---> eb03c7593be7
Step 12/17 : VOLUME /data
 ---> Running in 276ffa6ab135
Removing intermediate container 276ffa6ab135
 ---> 8c388a99f6ec
Step 13/17 : ENV LANG=C.UTF-8     LANGUAGE=en_US:en     LC_ALL=C.UTF-8     PYTHONIOENCODING=UTF-8     CHROME_SANDBOX=False     CHROME_BINARY=google-chrome-unstable     OUTPUT_DIR=/data
 ---> Running in 67497c78ee6d
Removing intermediate container 67497c78ee6d
 ---> d000923c6cfa
Step 14/17 : USER pptruser
 ---> Running in 2165ba6e9197
Removing intermediate container 2165ba6e9197
 ---> 1a4b71b4e2b3
Step 15/17 : WORKDIR /home/pptruser/app
 ---> Running in 8c461766a5cd
Removing intermediate container 8c461766a5cd
 ---> 4c2f3b6a4b63
Step 16/17 : ENTRYPOINT ["dumb-init", "--"]
 ---> Running in d443468d040f
Removing intermediate container d443468d040f
 ---> 723fba1ff206
Step 17/17 : CMD ["/bin/archive"]
 ---> Running in 8093f3faa0e4
Removing intermediate container 8093f3faa0e4
 ---> 1f9f3aca1d9a
Successfully built 1f9f3aca1d9a
Successfully tagged archivebox_archivebox:latest
WARNING: Image for service archivebox was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating archivebox_nginx_1      ... done
Creating archivebox_archivebox_1 ... done
```

## Trying to Add Links

```
/volume1/dkr/ArchiveBox$ sudo docker-compose exec archivebox /bin/archive /data/bookmarks.html
Password:
Traceback (most recent call last):
  File "/bin/archive", line 15, in <module>
    from links import links_after_timestamp
  File "/home/pptruser/app/archivebox/links.py", line 25, in <module>
    from util import (
  File "/home/pptruser/app/archivebox/util.py", line 20, in <module>
    from config import (
  File "/home/pptruser/app/archivebox/config.py", line 77, in <module>
    WGET_AUTO_COMPRESSION = USE_WGET and WGET_BINARY and (not run([WGET_BINARY, "--compression=auto", "--help"], stdout=DEVNULL, stderr=DEVNULL).returncode)
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '"wget"'
```

---

What happened to WGET? I have literally been trying to add this program for over 3 hours...

**Comment by pirate** [comment]
woah that super weird, never seen that happen before...

is it getting `'"wget"'` double-quoted somehow? maybe try adding `WGET_BINARY=wget` to the `environment:` section of the docker-compose file?

**Comment by shimizurei** [comment]
Same error with `WGET_BINARY="wget"` and `WGET_BINARY=wget`.

## Tested for WGET
```
wget --version
GNU Wget 1.19.1 built on linux-gnu.
```

## docker-compose.yml

```
version: '3'

services:
    archivebox:
        build: .   # replace this with nikisweeting/archivebox to use the docker-compose.yml file as a standalone file without avoid having to clone the repo (???)
        stdin_open: true
        tty: true
        env_file: ArchiveBox.conf
        environment:
            - USE_COLOR=False
            - SHOW_PROGRESS=False
            - FETCH_MEDIA=False
            - WGET_BINARY=wget
        volumes:
            - ./data:/data
        command: bash -c 'echo "https://github.com/pirate/ArchiveBox" | /bin/archive; tail -f /dev/null'  # archive the Github repo homepage as a starting point so the index doesn't just show an empty list to new users

    nginx:
        image: 'nginx'
        ports:
            - '8098:80'
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./data:/var/www
```

## Visiting the site
![archivebox](https://user-images.githubusercontent.com/3500094/68500366-8a929b80-0229-11ea-8871-bedb2eee11fb.PNG)

**Comment by shimizurei** [comment]
I ended up deleting it and starting over. I used `sudo` for everything Docker-related, starting from `docker-compose up -d` and it worked (i.e. `sudo docker-compose up -d`).
