### ISSUE TITLE
Exception in archive_methods.save_readability

### ISSUE THREAD

**Issue by jrruethe** [pirate/ArchiveBox#458]
When attempting to archive [this](https://forums.nasioc.com/forums/showthread.php?t=2803387&amp;highlight=big+brother&amp;page=3) link with Readability enabled, the following exception occurs.

From what I can tell so far, I think the exception occurs somewhere in [here](https://github.com/pirate/ArchiveBox/blob/master/archivebox/extractors/readability.py#L69) before `cmd` is instantiated [here](https://github.com/pirate/ArchiveBox/blob/master/archivebox/extractors/readability.py#L75), which means that `cmd` doesn't exist after the exception is caught and control makes it down to [here](https://github.com/pirate/ArchiveBox/blob/master/archivebox/extractors/readability.py#L109).

```
[√] [2020-08-26 21:10:43] "Big Brother is Watching - '17 WRX Limited and all '17 STI - Page 3 - NASIOC"
    https://forums.nasioc.com/forums/showthread.php?t=2803387&amp;highlight=big+brother&amp;page=3
    √ ./archive/1576899114
      > readability
    ! Failed to archive link: Exception: Exception in archive_methods.save_readability(Link(url=https://forums.nasioc.com/forums/showthread.php?t=2803387&amp;highlight=big+brother&amp;page=3))

Traceback (most recent call last):
  File "/app/archivebox/extractors/__init__.py", line 91, in archive_link
    result = method_function(link=link, out_dir=out_dir)
  File "/app/archivebox/util.py", line 111, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/extractors/readability.py", line 109, in save_readability
    cmd=cmd,
UnboundLocalError: local variable 'cmd' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/archivebox", line 33, in <module>
    sys.exit(load_entry_point('archivebox', 'console_scripts', 'archivebox')())
  File "/app/archivebox/cli/__init__.py", line 122, in main
    run_subcommand(
  File "/app/archivebox/cli/__init__.py", line 62, in run_subcommand
    module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
  File "/app/archivebox/cli/archivebox_add.py", line 78, in main
    add(
  File "/app/archivebox/util.py", line 111, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/main.py", line 572, in add
    archive_links(all_links, overwrite=overwrite, out_dir=out_dir)
  File "/app/archivebox/util.py", line 111, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/extractors/__init__.py", line 150, in archive_links
    archive_link(link, overwrite=overwrite, methods=methods, out_dir=link.link_dir)
  File "/app/archivebox/util.py", line 111, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/extractors/__init__.py", line 101, in archive_link
    raise Exception('Exception in archive_methods.save_{}(Link(url={}))'.format(
Exception: Exception in archive_methods.save_readability(Link(url=https://forums.nasioc.com/forums/showthread.php?t=2803387&amp;highlight=big+brother&amp;page=3))

```
This is with Docker image `nikisweeting/archivebox:0.4.21`

**Comment by cdvv7788** [comment]
Thanks for the report. I will check it.

**Comment by cdvv7788** [comment]
@jrruethe I sent a PR. A new version with the fix should come out next week. You can try the fix by using that branch directly for now.

**Comment by jrruethe** [comment]
Thank you very much!

**Comment by pirate** [comment]
This should be fixed now on `master`. If you still encounter any issues comment back here and I'll reopen the ticket.

To use `master` immediately without waiting for the next release you can build it directly from Github:
```bash
docker build 'https://github.com/pirate/ArchiveBox.git#master' -t archivebox
docker run -v $PWD:/data archivebox update
```
